{
  "comments": [
    {
      "key": {
        "uuid": "9abe1de1_5c45db6d",
        "filename": "python-os-faults.spec",
        "patchSetId": 2
      },
      "lineNbr": 66,
      "author": {
        "id": 113
      },
      "writtenOn": "2018-12-17T11:32:50Z",
      "side": 1,
      "message": "The Fedora CI seems to be failing to find the Ansible executable, maybe we\u0027ll need to add some fix to make the unit tests work?",
      "range": {
        "startLine": 66,
        "startChar": 0,
        "endLine": 66,
        "endChar": 31
      },
      "revId": "4aa51d76d51e05fb9eaaa353becff3f2ef838740",
      "serverId": "270e2033-b340-4cff-9539-693957ebf0e7",
      "unresolved": false
    },
    {
      "key": {
        "uuid": "9abe1de1_9cbdb36a",
        "filename": "python-os-faults.spec",
        "patchSetId": 2
      },
      "lineNbr": 108,
      "author": {
        "id": 128
      },
      "writtenOn": "2018-12-17T10:35:44Z",
      "side": 1,
      "message": "There should be a python_provide here.",
      "revId": "4aa51d76d51e05fb9eaaa353becff3f2ef838740",
      "serverId": "270e2033-b340-4cff-9539-693957ebf0e7",
      "unresolved": false
    },
    {
      "key": {
        "uuid": "9abe1de1_7cc09fe0",
        "filename": "python-os-faults.spec",
        "patchSetId": 2
      },
      "lineNbr": 127,
      "author": {
        "id": 128
      },
      "writtenOn": "2018-12-17T10:35:44Z",
      "side": 1,
      "message": "python_provide",
      "revId": "4aa51d76d51e05fb9eaaa353becff3f2ef838740",
      "serverId": "270e2033-b340-4cff-9539-693957ebf0e7",
      "unresolved": false
    }
  ]
}