{
  "comments": [
    {
      "key": {
        "uuid": "9abe1de1_9cbdb36a",
        "filename": "python-os-faults.spec",
        "patchSetId": 2
      },
      "lineNbr": 108,
      "author": {
        "id": 128
      },
      "writtenOn": "2018-12-17T10:35:44Z",
      "side": 1,
      "message": "There should be a python_provide here.",
      "revId": "4aa51d76d51e05fb9eaaa353becff3f2ef838740",
      "serverId": "270e2033-b340-4cff-9539-693957ebf0e7",
      "unresolved": false
    },
    {
      "key": {
        "uuid": "9abe1de1_7cc09fe0",
        "filename": "python-os-faults.spec",
        "patchSetId": 2
      },
      "lineNbr": 127,
      "author": {
        "id": 128
      },
      "writtenOn": "2018-12-17T10:35:44Z",
      "side": 1,
      "message": "python_provide",
      "revId": "4aa51d76d51e05fb9eaaa353becff3f2ef838740",
      "serverId": "270e2033-b340-4cff-9539-693957ebf0e7",
      "unresolved": false
    }
  ]
}